name = "Sakes Mods"
author = "Sakarias"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74b4122c45d70e6f0498fb33fb5c22750dfb296123c1c58bf488af6e945833dd"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
