name = "Sakes Mods"
author = "Sakarias"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c27037195a328b3449cd7d59e41a3623e1f5ef2ea52b13882fba5d3e87442c9"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
