name = "Sakes Mods"
author = "Sakarias"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fabe3d9f14013d74ad032ecef8e20584ce0468e817d44064ee46d4565264e77b"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
