name = "Sakes Mods"
author = "Sakarias"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c6e8ac551fe38788aea0504074a9995a4a23d27b20cb36331075adbf210475a"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
