name = "Sakes Mods"
author = "Sakarias"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1923640d618e2ffdecc7b8fa920acdc3b6b6dbc40232a7bac1be4dcaca1600c"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
