name = "Sakes Mods"
author = "Sakarias"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20785b3d39a27ac967b2bf295e7297029cca5edb9962129a7d68e5f32ae2301b"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
